import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

<header
  style={{
    borderBottom: "1px solid #eee",
    padding: "16px 24px",
    marginBottom: 30,
  }}
>
  <div
    style={{
      maxWidth: 1100,
      margin: "0 auto",
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
    }}
  >
    <a
      href="/"
      style={{
        fontWeight: 700,
        fontSize: 20,
        textDecoration: "none",
        color: "black",
      }}
    >
      TripDoc
    </a>

    <div style={{ display: "flex", gap: 20 }}>
      <a href="/" style={{ textDecoration: "none", color: "#444" }}>
        Home
      </a>

      <a href="/admin" style={{ textDecoration: "none", color: "#444" }}>
        Admin
      </a>
    </div>
  </div>
</header>

{children}

<footer
  style={{
    borderTop: "1px solid #eee",
    marginTop: 60,
    padding: 20,
    textAlign: "center",
    color: "#666",
  }}
>
  © {new Date().getFullYear()} TripDoc — Verified global opportunities
</footer>

</body>
    </html>
  );
}
